global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: otel-collector
    static_configs:
      - targets: ['otel-collector:9464']

  - job_name: node_exporter
    static_configs:
      - targets: ['host.docker.internal:9100']

  - job_name: pm2_metrics
    static_configs:
      - targets: ['host.docker.internal:9200']

  - job_name: nginx
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:9113']

